### PR TITLE
Quote cmake include path

### PR DESCRIPTION
**Pull request by krzyzanowskim**
quote include path that helps if path contains eg. a space

### CODE REVIEW

**Comment by milseman** [comment]
@compnerd can you take a look?

**Review by compnerd — APPROVED** [review]
I think that this could use a better commit message - it isn't immediately clear what it means.  Normally the include path would refer to the `CMAKE_MODULE_PATH` which shouldn't require quoting if handled properly IIRC.  This is in the generated config file and the quoting does matter here.

**Comment by krzyzanowskim** [comment]
> refer to the CMAKE_MODULE_PATH which shouldn't require quoting if handled properly IIRC

long story short: swift won't build if checkout to path with space

When building swift-project using [build-script](https://github.com/apple/swift/blob/main/utils/build-script) if fails randomly here and there, and this is one place where it fail to include cmake macros from a path with spaces.

**Comment by compnerd** [comment]
@krzyzanowskim I think that you misunderstood me, I agree that this site should be quoted.  I think that the "quote cmake include path" is a bit confusing is all.  This is an include, but the quoting is applied to a parameter.  The "CMake include path" is normally the `CMAKE_MODULE_PATH`, which is not being touched here and is confusing because you expect the diff to be different.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
I don't think that the commit message is worth keeping this open.  Going to merge it.

**Pull request merged**
