### PR TITLE
Remove allocatePortRightPair(), as move-only types are not permitted in tuples

### PR DESCRIPTION
**Pull request by loffgren**

### CODE REVIEW

**Comment by loffgren** [comment]
@swift-ci test

**Review by glessard — APPROVED** [review]
It's only temporary.

**Review by lorentey — APPROVED** [review]

**Comment by lorentey** [comment]
@swift-ci test macOS platform

**Comment by glessard** [comment]
@swift-ci please test macOS platform

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
@swift-ci please test

**Comment by glessard** [comment]
The last commit here deactivates `Mach.Port` entirely, due to a bug in the Swift compiler:
https://github.com/apple/swift/issues/66299 (rdar://110496872)
Once that is fixed we can re-activate `Mach.Port`.

**Comment by glessard** [comment]
@swift-ci please test macOS platform

**Pull request merged**
