### PR TITLE
Test Pull Request

### PR DESCRIPTION
**Pull request by shahmishal**

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
```
20:49:57 swift: /home/buildnode/jenkins/workspace/oss-swift-5.3-package-linux-ubuntu-16_04/swift/lib/SILGen/SILGenApply.cpp:4102: bool swift::Lowering::SILGenModule::isNonMutatingSelfIndirect(swift::SILDeclRef): Assertion `method->isNonMutating()' failed.
20:49:57 Stack dump:
```
@milseman is this know issue on Linux?

**Comment by milseman** [comment]
This is a known issue with 5.3 and toolchains from that timeframe. @slavapestov fixed it on main a few weeks ago.

**Comment by milseman** [comment]
(It reproduces on Darwin if you have a toolchain from that era with assertions enabled, but I'm guessing you're going with an SDK Swift)

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@shahmishal , should I close this PR?

**Pull request closed without merging**
