### PR TITLE
SystemInternals: support mocking on Windows

### PR DESCRIPTION
**Pull request by compnerd**
Add the Windows threading APIs for thread local storage.  Prefer the FLS
allocations over TLS allocations simply because they give us more
similar semantics.

### CODE REVIEW

**Comment by compnerd** [comment]
@milseman - let me know if you have an idea of structuring the change here better.  I suppose that we can create aliases for `ThreadLocalSet` and `ThreadLocalGet` for the cases where the return value is ignored, but the return conditions are different, which makes it a bit trickier.

**Comment by milseman** [comment]
Alright, I'll try to do some refactoring. Thanks for this!

**Comment by milseman** [comment]
https://github.com/apple/swift-system/pull/10

**Comment by milseman** [comment]
In https://github.com/apple/swift-system/pull/11, I actually implement this (I believe). Would you be open to me merging that PR after I slap on `@inline(__always)`, closing this PR, and you following up with more Windows support on top of that?

**Comment by milseman** [comment]
I think this can be closed. Feel free to reopen if I'm mistaken

**Pull request closed without merging**
