### PR TITLE
Tests: ignore XCTest manifest on newer Swift

### PR DESCRIPTION
**Pull request by compnerd**
This is motivated by the desire to build the test suite on Windows.
Newer versions of SPM have test discovery which obviates the test
manifest, which incidentally repairs the build on Windows while adopting
newer functionality and reducing management complexity.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Yes, I was conflicted about that.  It seems that it would be better to remove the file - it’s unlikely it will be maintained, test discovery is now default even, so why keep it?  But perhaps there are older environments that need to be supported?

**Comment by milseman** [comment]
We'll likely be bumping the tools version soon. I want to get a `FileDescriptor.readAll() -> some RAC<UInt8>`, etc.

**Comment by compnerd** [comment]
That is fair; what should we do in the meantime?  I would like to repair the test suite for Windows.

**Comment by Lukasa** [comment]
@milseman Is your plan to bump the tools version all the way to 5.7?

**Comment by lorentey** [comment]
@swift-ci test

**Pull request merged**
